apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
    - name: kubia
      image: pandulaweerasooriya/kubia
      ports:
        - containerPort: 8080
          protocol: TCP
